name: safesuit_bank
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3
  json_annotation: ^4.0.1
  provider: ^6.0.0
  local_auth: ^2.0.1
  flutter_local_notifications: ^17.0.0
  flutter_native_splash:
  qr_flutter: ^4.1.0
  cupertino_icons: ^1.0.2
  hexcolor: ^3.0.1
  
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  build_runner_core: ^7.3.0
  dio: ^5.0.0
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.2.2
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.1
  dio: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/json_data/retiroqr.json
  
  fonts:s
    - family: card
      fonts:
        - asset: assets/fonts/Anton-Regular.ttf